ingredienten = {
    "Groenten": {
        "Tomaat": "stuks",
        "Komkommer": "stuks",
        "Wortel": "gram",
        "Paprika": "stuks",
        "Spinazie": "gram",
        "Courgette": "stuks",
        "Broccoli": "gram",
        "Bloemkool": "gram",
        "Aubergine": "stuks",
        "Boerenkool": "gram",
        "Asperges": "stuks",
        "Radijs": "gram",
        "Selderij": "stuks",
        "Rucola": "gram",
        "Andijvie": "gram",
        "Spruitjes": "gram",
        "Prei": "stuks",
        "Champignons": "gram",
        "Knolselderij": "gram",
        "Venkel": "stuks",
        "Sperziebonen": "gram",
        "Snijbiet": "gram",
        "Paksoi": "stuks",
        "Lente-ui": "stuks",
        "Pompoen": "stuks",
        "Maïs": "gram"
    },
    "Fruit": {
        "Appel": "stuks",
        "Banaan": "stuks",
        "Aardbei": "gram",
        "Mango": "stuks",
        "Druif": "gram",
        "Peer": "stuks",
        "Perzik": "stuks",
        "Ananas": "stuks",
        "Kiwi": "stuks",
        "Watermeloen": "stuks",
        "Kers": "gram",
        "Bosbes": "gram",
        "Framboos": "gram",
        "Passievrucht": "stuks",
        "Pruim": "stuks",
        "Abrikoos": "stuks",
        "Vijg": "stuks",
        "Cranberry": "gram",
        "Granaatappel": "stuks",
        "Citroen": "stuks",
        "Limoen": "stuks",
        "Sinaasappel": "stuks",
        "Mandarijn": "stuks",
        "Papaja": "stuks",
        "Cactusvijg": "stuks"
    },
    "Vlees": {
        "Kipfilet": "gram",
        "Kippenvleugels": "gram",
        "Rundergehakt": "gram",
        "Biefstuk": "gram",
        "Varkenshaas": "gram",
        "Lamsbout": "gram",
        "Kalkoenfilet": "gram",
        "Eendenborst": "gram",
        "Spek": "gram",
        "Worstjes": "stuks",
        "Ham": "gram",
        "Wildzwijn": "gram",
        "Hertenbiefstuk": "gram",
        "Konijnenvlees": "gram"
    },
    "Vis & Zeevruchten": {
        "Zalm": "gram",
        "Tonijn": "gram",
        "Kabeljauw": "gram",
        "Garnalen": "gram",
        "Makreel": "gram",
        "Forel": "gram",
        "Sardines": "stuks",
        "Haring": "stuks",
        "Mosselen": "stuks",
        "Oesters": "stuks",
        "Krab": "gram",
        "Kreeft": "gram",
        "Ansjovis": "gram",
        "Rogvleugel": "gram",
        "Zeebaars": "gram",
        "Schol": "gram",
        "Tilapia": "gram"
    },
    "Granen & Zetmeel": {
        "Rijst": "gram",
        "Quinoa": "gram",
        "Havermout": "gram",
        "Tarwe": "gram",
        "Gerst": "gram",
        "Bulgur": "gram",
        "Couscous": "gram",
        "Polenta": "gram",
        "Spelt": "gram",
        "Amarant": "gram",
        "Boekweit": "gram",
        "Pasta": "gram",
        "Noodles": "gram",
        "Zoete aardappel": "gram",
        "Aardappel": "gram",
        "Yams": "gram"
    },
    "Zuivel": {
        "Melk": "liter",
        "Yoghurt": "liter",
        "Kaas": "gram",
        "Room": "ml",
        "Boter": "gram",
        "Kwark": "gram",
        "Ricotta": "gram",
        "Mascarpone": "gram",
        "Feta": "gram",
        "Parmezaan": "gram",
        "Mozzarella": "gram",
        "Geitenkaas": "gram",
        "Blauwe kaas": "gram",
        "Crème fraîche": "ml",
        "Karnemelk": "liter",
        "Skyr": "gram"
    },
    "Kruiden & Specerijen": {
        "Basilicum": "gram",
        "Peterselie": "gram",
        "Kurkuma": "gram",
        "Peper": "gram",
        "Kaneel": "gram",
        "Oregano": "gram",
        "Tijm": "gram",
        "Rozemarijn": "gram",
        "Koriander": "gram",
        "Dille": "gram",
        "Bieslook": "gram",
        "Komijn": "gram",
        "Paprikapoeder": "gram",
        "Kardemom": "gram",
        "Foelie": "gram",
        "Nootmuskaat": "gram",
        "Laurierblad": "stuks",
        "Chilivlokken": "gram",
        "Cayennepeper": "gram",
        "Knoflookpoeder": "gram",
        "Gemberpoeder": "gram",
        "Fenegriek": "gram",
        "Sumak": "gram"
    }
}
